apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: boutique

data:
  DB_HOST: expense-dev.cox4q0mwma2l.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: auth_db

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: boutique

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: ExpenseApp1
  AUTH_DB_URL: "postgresql://postgres:ExpenseApp1@expense-dev.cox4q0mwma2l.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=disable"

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  namespace: boutique

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth

          image: joindevops006/joindevops:auth

          ports:
            - containerPort: 3002

          env:
            - name: NODE_ENV
              value: development

            - name: PORT
              value: "3002"

          envFrom:
            - configMapRef:
                name: db-config

            - secretRef:
                name: db-secret

---
apiVersion: v1
kind: Service

metadata:
  name: auth
  namespace: boutique

spec:
  selector:
    app: auth

  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002

  type: ClusterIP