apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: boutique

data:
  DB_HOST: boutique-postgres
  DB_PORT: "5432"
  DB_NAME: auth_db


---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  namespace: boutique

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth

          image: joindevops006/joindevops:auth

          ports:
            - containerPort: 3002

          env:
            - name: NODE_ENV
              value: development

            - name: PORT
              value: "3002"

          envFrom:
            - configMapRef:
                name: db-config

---
apiVersion: v1
kind: Service

metadata:
  name: auth
  namespace: boutique

spec:
  selector:
    app: auth

  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002

  type: ClusterIP